# NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [1]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [2]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [3]:
# we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print(vec)
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)

[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [8]:
vc_1 = np.array([[1,2],[2,3],[3,4]])
print(vc_1)
print(vc_1.T)

[[1 2]
 [2 3]
 [3 4]]
[[1 2 3]
 [2 3 4]]


In [9]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,15)
print(vec2)
print('')
vec3 = np.arange(3,21,6)
print(vec3)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [10]:
vec_2=np.arange(1,20,2)
print(vec_2)

[ 1  3  5  7  9 11 13 15 17 19]


In [11]:
# this is to generate a set of random numbers between 2 intervals
vec4 = np.linspace(0,5,10)
print(vec4)
print('')
print(vec4.reshape(5,2))
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped)
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [14]:
vec_4 = np.linspace(0,1,10)
print(vec_4)
print(' ')
vec_4.reshape(5,2)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
 


array([[0.        , 0.11111111],
       [0.22222222, 0.33333333],
       [0.44444444, 0.55555556],
       [0.66666667, 0.77777778],
       [0.88888889, 1.        ]])

In [15]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [17]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


In [19]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))
vec_in = np.linalg.inv(mat)
print('')
prod_one=np.matmul(vec_in,mat)
print(prod_one)

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]

[[ 1.00000000e+00  0.00000000e+00 -2.77555756e-17]
 [ 2.77555756e-17  1.00000000e+00  2.77555756e-17]
 [-2.77555756e-17  0.00000000e+00  1.00000000e+00]]


In [20]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [37]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)
# lets do a little re-ordering around the matrices
rand_mat3 = rand_mat2.reshape(5,2,5)
print(rand_mat3)
print(rand_mat3.T)

[[0.69294341 0.72429028 0.12964511 0.589235   0.47041153]
 [0.56433551 0.66565439 0.70958609 0.85508877 0.59771722]
 [0.82674299 0.65814509 0.90580729 0.48763461 0.0603851 ]
 [0.90103068 0.19087984 0.56588705 0.69070472 0.71565944]
 [0.48227798 0.77467056 0.12234063 0.60640303 0.08860383]]

[[-0.45608479 -0.91380422  1.02199877  1.50412992 -1.67204579]
 [ 1.19378534  1.24787746 -1.9486176  -1.12548272 -0.01157607]
 [-0.80371422  0.12304049  0.8664427   0.5089781  -0.55392413]
 [ 0.11835159 -2.31660992  0.68101529  0.86639295 -0.40359788]
 [-0.59542786 -1.82708805  1.80782642  0.83929367  1.89699277]
 [ 0.17019753 -0.99283341  0.58787887 -0.28094539  0.07274461]
 [ 0.66034558  0.97541955  0.57377514  0.25892556 -0.80955646]
 [ 0.2208567   0.10268496  1.43220864 -1.13761557 -0.42661328]
 [ 0.12990132 -1.34444982  0.93919352 -0.2138971  -0.42188652]
 [ 0.72469775 -0.04716464  0.79053029  0.70909113  0.39360065]]
[[[-0.45608479 -0.91380422  1.02199877  1.50412992 -1.67204579]
  [ 1.1937853

In [27]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.5229345866956766
1.0061029652969231


In [28]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.08515060728367096
2.1783850237810296


In [ ]:
# break here for next video!

In [31]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])
type(rand_vec)
print(rand_vec[0:4])


[ 1.17674111 -0.73128836 -0.43869233  0.01964867  0.98865408  2.09426365
  0.24239653  1.06002389  1.31897799  1.87654044 -0.0076517   0.31044843
  0.55644278 -0.81442853  1.36532287  1.31163922 -0.37307789 -0.40690325
  1.5126575 ]
0.24239653156570654
[ 1.17674111 -0.73128836 -0.43869233  0.01964867]


In [32]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

[0.98865408 2.09426365 0.24239653 1.06002389 1.31897799]


In [33]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[1.17674111 0.01964867 0.24239653 1.87654044 0.55644278]


In [38]:
# what about matrices
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])
print(rand_mat3[1][1])

[[0.69294341 0.72429028 0.12964511 0.589235   0.47041153]
 [0.56433551 0.66565439 0.70958609 0.85508877 0.59771722]
 [0.82674299 0.65814509 0.90580729 0.48763461 0.0603851 ]
 [0.90103068 0.19087984 0.56588705 0.69070472 0.71565944]
 [0.48227798 0.77467056 0.12234063 0.60640303 0.08860383]]
0.7095860889494375
0.7095860889494375
[ 0.11835159 -2.31660992  0.68101529  0.86639295 -0.40359788]


In [39]:
#print(rand_mat[0:2,1:3])
print(rand_mat[1:2,1:4])

[[0.66565439 0.70958609 0.85508877]]


In [40]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[ 1.17674111 -0.73128836 -0.43869233  0.01964867  0.98865408  2.09426365
  0.24239653  1.06002389  1.31897799  1.87654044 -0.0076517   0.31044843
  0.55644278 -0.81442853  1.36532287  1.31163922 -0.37307789 -0.40690325
  1.5126575 ]

[ 1.17674111 -0.73128836 -0.43869233  4.          4.          2.09426365
  0.24239653  1.06002389  1.31897799  1.87654044 -0.0076517   0.31044843
  0.55644278 -0.81442853  1.36532287  1.31163922 -0.37307789 -0.40690325
  1.5126575 ]

[ 1.17674111 -0.73128836 -0.43869233  1.          2.          2.09426365
  0.24239653  1.06002389  1.31897799  1.87654044 -0.0076517   0.31044843
  0.55644278 -0.81442853  1.36532287  1.31163922 -0.37307789 -0.40690325
  1.5126575 ]


In [41]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[0.69294341 0.72429028 0.12964511 0.589235   0.47041153]
 [0.56433551 0.66565439 0.70958609 0.85508877 0.59771722]
 [0.82674299 0.65814509 0.90580729 0.48763461 0.0603851 ]
 [0.90103068 0.19087984 0.56588705 0.69070472 0.71565944]
 [0.48227798 0.77467056 0.12234063 0.60640303 0.08860383]]

[[0.69294341 0.72429028 0.12964511 0.589235   0.47041153]
 [0.56433551 0.66565439 0.70958609 0.         0.        ]
 [0.82674299 0.65814509 0.90580729 0.         0.        ]
 [0.90103068 0.19087984 0.56588705 0.69070472 0.71565944]
 [0.48227798 0.77467056 0.12234063 0.60640303 0.08860383]]


In [42]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)


[[0.69294341 0.72429028 0.12964511]
 [0.56433551 0.66565439 0.70958609]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [43]:
print(rand_mat)

[[3.         3.         3.         0.589235   0.47041153]
 [3.         3.         3.         0.         0.        ]
 [0.82674299 0.65814509 0.90580729 0.         0.        ]
 [0.90103068 0.19087984 0.56588705 0.69070472 0.71565944]
 [0.48227798 0.77467056 0.12234063 0.60640303 0.08860383]]


In [44]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)


[[99. 99. 99.]
 [99. 99. 99.]]
[[3.         3.         3.         0.589235   0.47041153]
 [3.         3.         3.         0.         0.        ]
 [0.82674299 0.65814509 0.90580729 0.         0.        ]
 [0.90103068 0.19087984 0.56588705 0.69070472 0.71565944]
 [0.48227798 0.77467056 0.12234063 0.60640303 0.08860383]]


In [ ]:
# break here for next video

In [45]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[-0.25675642 -0.72971334 -1.43379191  0.62090216  0.04027804  0.25173901
 -0.25815415  0.23236952 -0.602746   -1.23967834 -3.11303659 -0.43019576
 -0.39352317 -0.99601359  0.48716919]
[False False False  True  True  True False  True False False False False
 False False  True]
[0.62090216 0.04027804 0.25173901 0.23236952 0.48716919]


In [46]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[-0.45608479 -0.91380422  1.02199877  1.50412992 -1.67204579]
 [ 1.19378534  1.24787746 -1.9486176  -1.12548272 -0.01157607]
 [-0.80371422  0.12304049  0.8664427   0.5089781  -0.55392413]
 [ 0.11835159 -2.31660992  0.68101529  0.86639295 -0.40359788]
 [-0.59542786 -1.82708805  1.80782642  0.83929367  1.89699277]
 [ 0.17019753 -0.99283341  0.58787887 -0.28094539  0.07274461]
 [ 0.66034558  0.97541955  0.57377514  0.25892556 -0.80955646]
 [ 0.2208567   0.10268496  1.43220864 -1.13761557 -0.42661328]
 [ 0.12990132 -1.34444982  0.93919352 -0.2138971  -0.42188652]
 [ 0.72469775 -0.04716464  0.79053029  0.70909113  0.39360065]]
[1.02199877 1.50412992 1.19378534 1.24787746 0.12304049 0.8664427
 0.5089781  0.11835159 0.68101529 0.86639295 1.80782642 0.83929367
 1.89699277 0.17019753 0.58787887 0.07274461 0.66034558 0.97541955
 0.57377514 0.25892556 0.2208567  0.10268496 1.43220864 0.12990132
 0.93919352 0.72469775 0.79053029 0.70909113 0.39360065]


In [47]:

print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

[-0.25675642 -0.72971334 -1.43379191  0.62090216  0.04027804  0.25173901
 -0.25815415  0.23236952 -0.602746   -1.23967834 -3.11303659 -0.43019576
 -0.39352317 -0.99601359  0.48716919]

[-0.25675642 -0.72971334 -1.43379191 -5.          0.04027804  0.25173901
 -0.25815415  0.23236952 -0.602746   -1.23967834 -3.11303659 -0.43019576
 -0.39352317 -0.99601359  0.48716919]


In [48]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [49]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [50]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

[[-0.45608479 -0.91380422  1.02199877  1.50412992 -1.67204579]
 [ 1.19378534  1.24787746 -1.9486176  -1.12548272 -0.01157607]
 [-0.80371422  0.12304049  0.8664427   0.5089781  -0.55392413]
 [ 0.11835159 -2.31660992  0.68101529  0.86639295 -0.40359788]
 [-0.59542786 -1.82708805  1.80782642  0.83929367  1.89699277]
 [ 0.17019753 -0.99283341  0.58787887 -0.28094539  0.07274461]
 [ 0.66034558  0.97541955  0.57377514  0.25892556 -0.80955646]
 [ 0.2208567   0.10268496  1.43220864 -1.13761557 -0.42661328]
 [ 0.12990132 -1.34444982  0.93919352 -0.2138971  -0.42188652]
 [ 0.72469775 -0.04716464  0.79053029  0.70909113  0.39360065]]



In [51]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

[[3.         3.         3.         0.589235   0.47041153]
 [3.         3.         3.         0.         0.        ]
 [0.82674299 0.65814509 0.90580729 0.         0.        ]
 [0.90103068 0.19087984 0.56588705 0.69070472 0.71565944]
 [0.48227798 0.77467056 0.12234063 0.60640303 0.08860383]]

[[-0.45608479 -0.91380422  1.02199877  1.50412992 -1.67204579]
 [ 1.19378534  1.24787746 -1.9486176  -1.12548272 -0.01157607]
 [-0.80371422  0.12304049  0.8664427   0.5089781  -0.55392413]
 [ 0.11835159 -2.31660992  0.68101529  0.86639295 -0.40359788]
 [-0.59542786 -1.82708805  1.80782642  0.83929367  1.89699277]
 [ 0.17019753 -0.99283341  0.58787887 -0.28094539  0.07274461]
 [ 0.66034558  0.97541955  0.57377514  0.25892556 -0.80955646]
 [ 0.2208567   0.10268496  1.43220864 -1.13761557 -0.42661328]
 [ 0.12990132 -1.34444982  0.93919352 -0.2138971  -0.42188652]
 [ 0.72469775 -0.04716464  0.79053029  0.70909113  0.39360065]]
[[3.         3.         3.         0.589235   0.47041153]
 [3.         3.    

In [52]:
# we can also save/load as text files...but only single variables
np.savetxt('txt1.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('txt1.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)

[[3.         3.         3.         0.589235   0.47041153]
 [3.         3.         3.         0.         0.        ]
 [0.82674299 0.65814509 0.90580729 0.         0.        ]
 [0.90103068 0.19087984 0.56588705 0.69070472 0.71565944]
 [0.48227798 0.77467056 0.12234063 0.60640303 0.08860383]]

[[3.         3.         3.         0.589235   0.47041153]
 [3.         3.         3.         0.         0.        ]
 [0.82674299 0.65814509 0.90580729 0.         0.        ]
 [0.90103068 0.19087984 0.56588705 0.69070472 0.71565944]
 [0.48227798 0.77467056 0.12234063 0.60640303 0.08860383]]


In [ ]:
#End of Numpy Lab